// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tzznkrboeauohmwrowlj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR6em5rcmJvZWF1b2htd3Jvd2xqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4NzIyMTEsImV4cCI6MjA2OTQ0ODIxMX0.pwcfV-1dRMGHC468YlJ1ufYMjJJXK8cpYOvqK-yOVko";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});